### ISSUE TITLE
Spring Boot Project Structure

### ISSUE THREAD

**Issue by celikgumusdag** [tuncgumusdag/phone-book-api#3]
Dear Tunç,

Could you please change your project structure and divide your java classes under appropriate package?

An example structure:

[![image](https://user-images.githubusercontent.com/3326972/69144076-c56abe00-0aca-11ea-8edd-ad7f3eeda15f.png)](Example)

**Comment by tuncgumusdag** [comment]
Fixed the project structure as you've requested. #4
